CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN (
      # Write your MySQL query statement below.
        WITH OLD AS (SELECT SALARY, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RNK FROM EMPLOYEE)
        SELECT DISTINCT SALARY FROM OLD WHERE RNK = N
  );
END